name: market_mobile
description: OnlineMarket Ana Sayfa
publish_to: 'none'

environment:
  sdk: ">=2.18.0 <3.0.0"
  
dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  provider: ^6.1.0
  http: ^0.13.6


flutter:
  uses-material-design: true

  assets:
    - assets/icons/
