name: market_mobile
description: OnlineMarket Ana Sayfa
publish_to: 'none'

environment:
  sdk: ">=2.18.0 <3.0.0"
  
dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  provider: ^6.1.0
  http: ^1.1.0
  flutter_markdown: ^0.6.17
  firebase_core: ^2.24.2
  firebase_database: ^10.3.8
  google_fonts: ^6.1.0


flutter:
  uses-material-design: true

  assets:
    - assets/icons/
